version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./config/env/local
    volumes:
      - "./app/src:/app/src/"
      - "./app/apache/:/etc/apache2/sites-enabled/"
      - "./app/log:/app/log"
    depends_on:
      - db
      - migration
    networks:
      - backend

  migration:
    build:
      context: ./migration
      dockerfile: Dockerfile
    networks:
      - backend
    env_file:
      - ./config/env/local
    volumes:
      - "./migration:/app"
    depends_on:
      - db

  db:
    image: "mysql:8"
    #privileged: true
    networks:
      - backend
#    ports:
#      - "3306:3306"
    env_file:
      - ./config/env/local

networks:
  backend:
    driver: bridge
