apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- secret.yaml
images:
- name: joidevops/app
  newName: joidevops/app
  newTag: 3d79a08
- name: joidevops/migration
  newName: joidevops/migration
  newTag: 3d79a08
