apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- secret.yaml
images:
- name: showerlee/app
  newTag: 44e9004
- name: showerlee/migration
  newTag: 44e9004
