apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- secret.yaml
- ingress.yaml
images:
- name: showerlee/app
  newTag: 13c366f
- name: showerlee/migration
  newTag: 13c366f
