apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- secret.yaml
- configmap.yaml
images:
- name: showerlee/app
  newTag: f70daed
- name: showerlee/migration
  newTag: f70daed
