apiVersion: v1
kind: Secret
metadata:
  name: db-info
data:
  DB_HOST: ZGV2b3BzLWpvaS1kYg==
  DB_NAME: ZGV2b3Bz
  DB_USER: aWFtbm9vbmU=
  DB_PASSWORD: SGVhck1lUm9hciE=
  DB_ROOT_PASSWORD: QXNIaWdoYXNIb25vcg==
