apiVersion: v1
kind: Service
metadata:
  name: devops-joi
spec:
  type: NodePort
  selector:
    app: devops-joi
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32100
---
apiVersion: v1
kind: Service
metadata:
  name: devops-joi-db
spec:
  selector:
    app: devops-joi-db
  ports:
    - protocol: TCP
      port: 3306
