#!/bin/bash -ev

export APACHE_LOG_DIR=${APACHE_LOG_DIR:-/var/log/apache2}
export APACHE_RUN_GROUP=${APACHE_RUN_GROUP:-www-data}
export APACHE_RUN_USER=${APACHE_RUN_USER:-www-data}
export APACHE_PID_FILE=${APACHE_PID_FILE:-/var/run/apache2/apache2.pid}
export APACHE_LOCK_DIR=${APACHE_LOCK_DIR:-/var/lock/apache2}

exec /usr/sbin/apache2 -DFOREGROUND
