#!/bin/bash -e

cd $(dirname $0)/..
source ./auto/set-env-helpers

[ -f ./config/cr-credential ] && source ./config/cr-credential

display_status "Login to registry"
docker login -u ${ALICR_USER} -p ${ALICR_PASS} ${ALICR_PREFIX}
