#!/bin/bash -e

cd $(dirname $0)/..
source ./auto/set-env-helpers

kustomize edit set image joidevops/app=${REPO_NAMESPACE}/app:${GIT_HASH} joidevops/migration=${REPO_NAMESPACE}/migration:${GIT_HASH}

kustomize build . -o kustomize-output.yaml
