#!/bin/bash -e

cd $(dirname $0)/../k8s
#source ./auto/set-env-helpers

#kustomize edit set image joidevops/app:${GIT_HASH} joidevops/migration:${GIT_HASH}
#kustomize build . -o kustomize-output.yaml
#
#kubectl apply -f k8s/kustomize-output.yaml
#
#kubectl rollout status -w deployment/devops-joi

# deploy ns
kubectl apply -f namespace.yaml

# create secret
kubectl apply -f secret.yaml

# deploy service
kubectl apply -f service.yaml

# deploy
kubectl apply -f deployment.yaml
