#! /bin/bash -e
#
cd $(dirname $0)/..
source ./auto/set-env-helpers

CONF_DIR="./terraform/$1"

if [[ $1 == 'aws' ]]; then
  echo AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:?AWS_ACCESS_KEY_ID must be set}" > ./tmp/env
  echo AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:?AWS_SECRET_ACCESS_KEY must be set}" >> ./tmp/env
  echo AWS_SESSION_TOKEN="${AWS_SESSION_TOKEN:?AWS_SESSION_TOKEN must be set}" >> ./tmp/env
fi

terraform -chdir=${CONF_DIR} destroy -auto-approve

rm -rf ./tmp/env
