#! /bin/bash -e
#

cd $(dirname $0)/..
source ./auto/set-env-helpers

docker-compose --project-name ${PROJECTNAME} build \
  --build-arg GIT_HASH=${GIT_HASH} \
  --build-arg TAG_TIME=${TAG_TIME}

docker-compose --project-name ${PROJECTNAME} up app
