#!/bin/bash -e

REPO_NAMESPACE="bthlt"
APP_NAME="app"
MIGRATION_NAME="migration"
GIT_HASH=$(git rev-parse --short HEAD)
TAG_TIME=$(date +'%Y%m%d%H%M')
PROJECT_NAME=${PROJECT_NAME:-joi}
KUBE_CONFILE="./tmp/kubeconfig.txt"
ALICR_PREFIX="registry.ap-southeast-1.aliyuncs.com"

display_status() {
  echo ">>> $1 <<<" 1>&2
}

function terraform() {

  [[ ! -f ./terraform/aws/tmp/.env ]] && echo > ./terraform/aws/tmp/.env

  docker run --rm \
  -v ${PWD}:/working \
  -w /working \
  --env-file ./terraform/aws/tmp/.env \
  hashicorp/terraform $@
}

function kubectl() {
  docker run --rm \
  -v ${PWD}/${KUBE_CONFILE}:/.kube/config \
  -v ${PWD}:/working \
  -w /working \
  bitnami/kubectl $@
}

function kustomize() {
  docker run --rm \
  -v ${PWD}/k8s:/working \
  -w /working \
  bitlayer/kustomize:v2.1.0 $@
}
