name: deploy_interview

on:
  push:
    branches:
    - main
    - joi-**

jobs:
  release-docker-images-to-alicr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # 1.1 Login to ACR
    - name: Login to ACR with the AccessKey pair
      env:
        ALICR_USER: "${{ secrets.ALICR_USER }}"
        ALICR_PASS: "${{ secrets.ALICR_PASS }}"
        ALICR_PREFIX: "${{ secrets.ALICR_PREFIX }}"
      run: |
        ./auto/auth-with-alicr

    # 1.2 Buid and push image to ACR
    - name: Build and push image to ACR
      run: |
        ./auto/release-docker-images-to-alicr
      env:
        ALICR_USER: "${{ secrets.ALICR_USER }}"
        ALICR_PASS: "${{ secrets.ALICR_PASS }}"

  release-docker-images-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # 2.1 Login to Dockerhub
    - name: Login to DockerHub
      env:
        DOCKER_USER: "${{ secrets.DOCKER_USER }}"
        DOCKER_PASS: "${{ secrets.DOCKER_PASS }}"
      run: |
        ./auto/auth-with-dockerhub

    # 2.2 Buid and push image to Dockerhub
    - name: Build and push image to DockerHub
      run: |
        ./auto/release-docker-images-to-dockerhub
      env:
        DOCKER_USER: "${{ secrets.DOCKER_USER }}"
        DOCKER_PASS: "${{ secrets.DOCKER_PASS }}"
