name: deploy_interview

on:
  push:
    branches:
    - pipeline

jobs:
  release-docker-images-to-ali:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # 1.1 Login to ACR
    - name: Login to DockerHub
      run: ./auto/auth-with-ali-cr

    # 1.2 Buid and push image to ACR
    - name: Build and push image to DockerHub
      run: |
        ./auto/release-docker-images-to-ali

jobs:
  release-docker-images-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # 1.1 Login to ACR
    - name: Login to DockerHub
      run: ./auto/auth-with-dockerhub

    # 1.2 Buid and push image to ACR
    - name: Build and push image to DockerHub
      run: |
        ./auto/release-docker-images-to-dockerhub