name: deploy_interview

on:
  push:
    branches:
    - main

jobs:
  release-docker-images-to-alicr:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Buid and push image to ACR
    - name: Build and push image to ACR
      run: |
        ./auto/release-docker-images-to-alicr
      env:
        ALICR_USER: "${{ secrets.ALICR_USER }}"
        ALICR_PASS: "${{ secrets.ALICR_PASS }}"

  release-docker-images-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Buid and push image to Dockerhub
    - name: Build and push image to DockerHub
      run: |
        ./auto/release-docker-images-to-dockerhub
      env:
        DOCKER_USER: "${{ secrets.DOCKER_USER }}"
        DOCKER_PASS: "${{ secrets.DOCKER_PASS }}"
