name: deploy_interview

on:
  push:
    branches:
    - pipeline

jobs:
  build-app-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # 1.1 Login to ACR
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        access-key-id: "${{ secrets.DOCKER_USER }}"
        access-key-secret: "${{ secrets.DOCKER_PASS }}"

    # 1.2 Buid and push image to ACR
    - name: Build and push image to DockerHub
      run: |
        bash ./auto/build-docker-images
        echo upload image